import { Inter } from "next/font/google";
import "./globals.scss";
import AppContainer from "@/components/app.container";
import AppFooter from "@/components/app.footer";
import AppHeader from "@/components/app.header";
import HomeStatistics from "@/components/home.statistics";
import HomeStatisticsContainer from "@/components/home.statistics-container";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="vi">
      <body className={inter.className}>
        <AppHeader />
        <AppContainer>
          <div>{children}</div>
        </AppContainer>
        {/* <HomeStatisticsContainer></HomeStatisticsContainer> */}
        <HomeStatistics />
        <AppFooter />
      </body>
    </html>
  );
}
